trigger:
  branches:
    include:
      - main
      - develop  # Adjust as needed for the branches you want to trigger the pipeline

pool:
  vmImage: 'windows-latest'  # Or use 'ubuntu-latest' if preferred

steps:
# Install Java if needed
- task: JavaToolInstaller@1
  inputs:
    versionSpec: '21'  # Specify the Java version you need (e.g., 11 or 17)
    cleanDestinationDirectory: true

# Build the project using Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'  # Path to your pom.xml file
    goals: 'clean install'
    options: '-DskipTests=true -Dmaven.test.failure.ignore=true'  # Skip tests during build, handle failures

# Run Selenium Tests
- script: |
    mvn test -Dmaven.test.failure.ignore=true  # Run tests, ignore failures to allow reporting
  displayName: 'Run Selenium Tests'
  continueOnError: true  # Proceed with pipeline even if tests fail

# Publish test results
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/surefire-reports/TEST-*.xml'  # Adjust to match Surefire output
    testRunTitle: 'Selenium Test Results'
  displayName: 'Publish Test Results'
