trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'windows-latest'  # Or use 'ubuntu-latest' if preferred

steps:
# Install Java with specified architecture and source
- task: JavaToolInstaller@1
  inputs:
    versionSpec: '11'                  # Specify the Java version you need
    jdkArchitectureOption: 'x64'       # Set architecture (x64 or x86)
    jdkSourceOption: 'PreInstalled'     # Use the pre-installed JDK on the agent
    cleanDestinationDirectory: true

# Build the project using Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'            # Path to your pom.xml file
    goals: 'clean test'                 # Run tests during the build
    options: '-Dmaven.test.failure.ignore=true'  # Ignore test failures
  displayName: 'Build with Maven'

# Publish test results
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/target/surefire-reports/TEST-*.xml'  # Adjust to match the path of Surefire reports
    testRunTitle: 'Selenium Test Results'
  displayName: 'Publish Test Results'
