trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'windows-latest'  # Or use 'ubuntu-latest' if preferred

steps:
# Install Java with specified architecture
- task: JavaToolInstaller@1
  inputs:
    versionSpec: '11'                  # Specify the Java version you need
    jdkArchitectureOption: 'x64'       # Set architecture (x64 or x86)
    cleanDestinationDirectory: true

# Build the project using Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'            # Path to your pom.xml file
    goals: 'clean install'
    options: '-DskipTests=true -Dmaven.test.failure.ignore=true'
  displayName: 'Build with Maven'

# Run Selenium Tests
- script: |
    mvn test -Dmaven.test.failure.ignore=true
  displayName: 'Run Selenium Tests'
  continueOnError: true

# Publish test results
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'Selenium Test Results'
  displayName: 'Publish Test Results'
