trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'windows-latest'  # Or use 'ubuntu-latest' if preferred

steps:
# Install Java with specified architecture and source
- task: JavaToolInstaller@1
  inputs:
    versionSpec: '11'                  # Specify the Java version you need
    jdkArchitectureOption: 'x64'       # Set architecture (x64 or x86)
    jdkSourceOption: 'PreInstalled'     # Use the pre-installed JDK on the agent
    cleanDestinationDirectory: true

# Build the project using Maven
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false'

# Run Selenium Tests
- script: |
    mvn test -Dmaven.test.failure.ignore=true
  displayName: 'Run Selenium Tests'
  continueOnError: true

# Publish test results
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'Selenium Test Results'
  displayName: 'Publish Test Results'


